extern crate cbindgen;

use std::env;
use std::path::Path;

fn main() {
  let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
  let header = Path::new("target").join("wardstone.h");

  cbindgen::Builder::new()
    .with_header("/* Code generated by cbindgen. DO NOT EDIT. */")
    .with_crate(crate_dir)
    .with_language(cbindgen::Language::C)
    .with_include_guard("WARDSTONE_H")
    .generate()
    .expect("Unable to generate bindings")
    .write_to_file(header);
}
